// priority: 0

settings.logAddedRecipes = false
settings.logRemovedRecipes = false
settings.logSkippedRecipes = false
settings.logErroringRecipes = true

onEvent('recipes', event => {
	// Change recipes here
	// event.remove({output: 'minecraft:stone_pickaxe'})
	// event.remove({input: '#forge:dusts/redstone'})
	// event.remove({mod: 'quartzchests'})
	// event.remove({id: 'minecraft:glowstone'})
	
	// Delete Creative and Debug Items
	event.remove({output: '#excompressum:baits'})
	event.remove({output: '#excompressum:heavy_sieve'})
	event.remove({output: '#excompressum:sieves'})
	event.remove({output: 'ae2:debug_card'})
	event.remove({output: 'ae2:debug_eraser'})
	event.remove({output: 'ae2:debug_meteorite_placer'})
	event.remove({output: 'ae2:debug_replicator_card'})
	event.remove({output: 'alexsmobs:falconry_glove_hand'})
	event.remove({output: 'alexsmobs:falconry_glove_inventory'})
	event.remove({output: 'alexsmobs:red_sand_circle'})
	event.remove({output: 'alexsmobs:sand_circle'})
	event.remove({output: 'alexsmobs:skelewag_sword_hand'})
	event.remove({output: 'alexsmobs:skelewag_sword_inventory'})
	event.remove({output: 'alexsmobs:tab_icon'})
	event.remove({output: 'alexsmobs:vine_lasso_hand'})
	event.remove({output: 'alexsmobs:vine_lasso_inventory'})
	event.remove({output: 'autooredictconv:converter'})
	event.remove({output: 'citadel:debug'})
	event.remove({output: 'citadel:effect_item'})
	event.remove({output: 'citadel:fancy_item'})
	event.remove({output: 'computercraft:computer_command'})
	event.remove({output: 'create_things_and_misc:hot_air_ballon_spawn_egg'})
	event.remove({output: 'excompressum:auto_heavy_sieve'})
	event.remove({output: 'excompressum:auto_sieve'})
	event.remove({output: 'excompressum:bat_zapper'})
	event.remove({output: 'excompressum:chicken_stick'})
	event.remove({output: 'excompressum:evolved_orechid'})
	event.remove({output: 'excompressum:iron_mesh'})
	event.remove({output: 'excompressum:mana_hammer'})
	event.remove({output: 'excompressum:mana_sieve'})
	event.remove({output: 'excompressum:ore_smasher'})
	event.remove({output: 'exnihilosequentia:bee_doll'})
	event.remove({output: 'exnihilosequentia:blaze_doll'})
	event.remove({output: 'exnihilosequentia:crafting_doll'})
	event.remove({output: 'exnihilosequentia:diamond_mesh'})
	event.remove({output: 'exnihilosequentia:emerald_mesh'})
	event.remove({output: 'exnihilosequentia:end_cake'})
	event.remove({output: 'exnihilosequentia:enderman_doll'})
	event.remove({output: 'exnihilosequentia:flint_mesh'})
	event.remove({output: 'exnihilosequentia:guardian_doll'})
	event.remove({output: 'exnihilosequentia:iron_mesh'})
	event.remove({output: 'exnihilosequentia:shulker_doll'})
	event.remove({output: 'exnihilosequentia:string_mesh'})
	event.remove({output: 'extendedcrafting:recipe_maker'})
	event.remove({output: 'ftbquests:barrier'})
	event.remove({output: 'ftbquests:custom_icon'})
	event.remove({output: 'ftbquests:detector'})
	event.remove({output: 'ftbquests:loot_crate_opener'})
	event.remove({output: 'ftbquests:missing_item'})
	event.remove({output: 'ftbquests:stage_barrier'})
	event.remove({output: 'mcjtylib:multipart'})
	event.remove({output: 'mekanism:bounding_block'})
	event.remove({output: 'minecraft:barrier'})
	event.remove({output: 'minecraft:bedrock'})
	event.remove({output: 'minecraft:bundle'})
	event.remove({output: 'minecraft:chain_command_block'})
	event.remove({output: 'minecraft:command_block_minecart'})
	event.remove({output: 'minecraft:command_block'})
	event.remove({output: 'minecraft:filled_map'})
	event.remove({output: 'minecraft:jigsaw'})
	event.remove({output: 'minecraft:knowledge_book'})
	event.remove({output: 'minecraft:light'})
	event.remove({output: 'minecraft:repeating_command_block'})
	event.remove({output: 'minecraft:structure_block'})
	event.remove({output: 'minecraft:structure_void'})
	event.remove({output: 'storagedrawers:creative_vending_upgrade'})
	event.remove({output: 'supplementaries:checker_vertical_slab'})
	event.remove({output: 'supplementaries:pancake_disc'})
	event.remove({output: 'supplementaries:placeable_item'})
	event.remove({output: 'unusualend:dragon_lamp_on'})
	event.remove({output: 'unusualend:fading_block_on'})
	event.remove({output: 'unusualend:infused_ender_respawn_altar'})
	event.remove({output: 'wormhole:portal'})
	
	event.remove({input: '#excompressum:baits'})
	event.remove({input: '#excompressum:heavy_sieve'})
	event.remove({input: '#excompressum:sieves'})
	event.remove({input: 'ae2:debug_card'})
	event.remove({input: 'ae2:debug_eraser'})
	event.remove({input: 'ae2:debug_meteorite_placer'})
	event.remove({input: 'ae2:debug_replicator_card'})
	event.remove({input: 'alexsmobs:falconry_glove_hand'})
	event.remove({input: 'alexsmobs:falconry_glove_inventory'})
	event.remove({input: 'alexsmobs:red_sand_circle'})
	event.remove({input: 'alexsmobs:sand_circle'})
	event.remove({input: 'alexsmobs:skelewag_sword_hand'})
	event.remove({input: 'alexsmobs:skelewag_sword_inventory'})
	event.remove({input: 'alexsmobs:tab_icon'})
	event.remove({input: 'alexsmobs:vine_lasso_hand'})
	event.remove({input: 'alexsmobs:vine_lasso_inventory'})
	event.remove({input: 'autooredictconv:converter'})
	event.remove({input: 'citadel:debug'})
	event.remove({input: 'citadel:effect_item'})
	event.remove({input: 'citadel:fancy_item'})
	event.remove({input: 'computercraft:computer_command'})
	event.remove({input: 'create_things_and_misc:hot_air_ballon_spawn_egg'})
	event.remove({input: 'excompressum:auto_heavy_sieve'})
	event.remove({input: 'excompressum:auto_sieve'})
	event.remove({input: 'excompressum:bat_zapper'})
	event.remove({input: 'excompressum:chicken_stick'})
	event.remove({input: 'excompressum:evolved_orechid'})
	event.remove({input: 'excompressum:iron_mesh'})
	event.remove({input: 'excompressum:mana_hammer'})
	event.remove({input: 'excompressum:mana_sieve'})
	event.remove({input: 'excompressum:ore_smasher'})
	event.remove({input: 'exnihilosequentia:bee_doll'})
	event.remove({input: 'exnihilosequentia:blaze_doll'})
	event.remove({input: 'exnihilosequentia:crafting_doll'})
	event.remove({input: 'exnihilosequentia:diamond_mesh'})
	event.remove({input: 'exnihilosequentia:emerald_mesh'})
	event.remove({input: 'exnihilosequentia:end_cake'})
	event.remove({input: 'exnihilosequentia:enderman_doll'})
	event.remove({input: 'exnihilosequentia:flint_mesh'})
	event.remove({input: 'exnihilosequentia:guardian_doll'})
	event.remove({input: 'exnihilosequentia:iron_mesh'})
	event.remove({input: 'exnihilosequentia:shulker_doll'})
	event.remove({input: 'exnihilosequentia:string_mesh'})
	event.remove({input: 'extendedcrafting:recipe_maker'})
	event.remove({input: 'ftbquests:barrier'})
	event.remove({input: 'ftbquests:custom_icon'})
	event.remove({input: 'ftbquests:detector'})
	event.remove({input: 'ftbquests:loot_crate_opener'})
	event.remove({input: 'ftbquests:missing_item'})
	event.remove({input: 'ftbquests:stage_barrier'})
	event.remove({input: 'mcjtylib:multipart'})
	event.remove({input: 'mekanism:bounding_block'})
	event.remove({input: 'minecraft:barrier'})
	event.remove({input: 'minecraft:bedrock'})
	event.remove({input: 'minecraft:bundle'})
	event.remove({input: 'minecraft:chain_command_block'})
	event.remove({input: 'minecraft:command_block_minecart'})
	event.remove({input: 'minecraft:command_block'})
	event.remove({input: 'minecraft:filled_map'})
	event.remove({input: 'minecraft:jigsaw'})
	event.remove({input: 'minecraft:knowledge_book'})
	event.remove({input: 'minecraft:light'})
	event.remove({input: 'minecraft:repeating_command_block'})
	event.remove({input: 'minecraft:structure_block'})
	event.remove({input: 'minecraft:structure_void'})
	event.remove({input: 'storagedrawers:creative_vending_upgrade'})
	event.remove({input: 'supplementaries:checker_vertical_slab'})
	event.remove({input: 'supplementaries:pancake_disc'})
	event.remove({input: 'supplementaries:placeable_item'})
	event.remove({input: 'unusualend:dragon_lamp_on'})
	event.remove({input: 'unusualend:fading_block_on'})
	event.remove({input: 'unusualend:infused_ender_respawn_altar'})
	event.remove({input: 'wormhole:portal'})

	// Oganesson
	event.remove({input: 'chemlib:oganesson'})
	event.remove({output: 'chemlib:oganesson'})
	event.remove({id: 'alchemistry:dissolver/dragon_breath'})
	
})

// Listen to item tag event
onEvent('tags.items', event => {
	// Get the #forge:tag tag collection and add mod:item to it
	// event.add('forge:ingots/andesite_alloy', 'create:andesite_alloy')
	// event.add('minecraft:lectern_books', 'eccentrictome:tome')

	// Stone Ore Dictionary
	event.add('forge:ores/stone/aluminum', 'immersiveengineering:ore_aluminum')
	event.add('forge:ores/stone/aluminum', 'tinkers_reforged:aluminum_ore')
	event.add('forge:ores/stone/certus_quartz', 'ae2:quartz_ore')
	event.add('forge:ores/stone/cinnabar', 'thermal:cinnabar_ore')
	event.add('forge:ores/stone/coal', 'minecraft:coal_ore')
	event.add('forge:ores/stone/copper', 'minecraft:copper_ore')
	event.add('forge:ores/stone/diamond', 'minecraft:diamond_ore')
	event.add('forge:ores/stone/dimensional_shard', 'rftoolsbase:dimensionalshard_overworld')
	event.add('forge:ores/stone/emerald', 'minecraft:emerald_ore')
	event.add('forge:ores/stone/fluorite', 'mekanism:fluorite_ore')
	event.add('forge:ores/stone/gold', 'minecraft:gold_ore')
	event.add('forge:ores/stone/iron', 'minecraft:iron_ore')
	event.add('forge:ores/stone/lapis', 'minecraft:lapis_ore')
	event.add('forge:ores/stone/lead', 'immersiveengineering:ore_lead')
	event.add('forge:ores/stone/lead', 'mekanism:lead_ore')
	event.add('forge:ores/stone/lead', 'thermal:lead_ore')
	event.add('forge:ores/stone/nickel', 'immersiveengineering:ore_nickel')
	event.add('forge:ores/stone/nickel', 'thermal:nickel_ore')
	event.add('forge:ores/stone/niter', 'thermal:niter_ore')
	event.add('forge:ores/stone/osmium', 'mekanism:osmium_ore')
	event.add('forge:ores/stone/prosperity', 'mysticalagriculture:prosperity_ore')
	event.add('forge:ores/stone/red_beryl', 'tinkers_reforged:red_beryl_ore')
	event.add('forge:ores/stone/redstone', 'minecraft:redstone_ore')
	event.add('forge:ores/stone/silver', 'immersiveengineering:ore_silver')
	event.add('forge:ores/stone/silver', 'thermal:silver_ore')
	event.add('forge:ores/stone/sulfur', 'thermal:sulfur_ore')
	event.add('forge:ores/stone/tin', 'mekanism:tin_ore')
	event.add('forge:ores/stone/tin', 'thermal:tin_ore')
	event.add('forge:ores/stone/uranium', 'immersiveengineering:ore_uranium')
	event.add('forge:ores/stone/uranium', 'mekanism:uranium_ore')
	event.add('forge:ores/stone/zinc', 'create:zinc_ore')

	// Deepslate Ore Dictionary
	event.add('forge:ores/deepslate/aluminum', 'immersiveengineering:deepslate_ore_aluminum')
	event.add('forge:ores/deepslate/aluminum', 'tinkers_reforged:deepslate_aluminum_ore')
	event.add('forge:ores/deepslate/certus_quartz', 'ae2:deepslate_quartz_ore')
	event.add('forge:ores/deepslate/cinnabar', 'thermal:deepslate_cinnabar_ore')
	event.add('forge:ores/deepslate/coal', 'minecraft:deepslate_coal_ore')
	event.add('forge:ores/deepslate/copper', 'minecraft:deepslate_copper_ore')
	event.add('forge:ores/deepslate/diamond', 'minecraft:deepslate_diamond_ore')
	event.add('forge:ores/deepslate/emerald', 'minecraft:deepslate_emerald_ore')
	event.add('forge:ores/deepslate/epidote', 'tinkers_reforged:deepslate_epidote_ore')
	event.add('forge:ores/deepslate/fluorite', 'mekanism:deepslate_fluorite_ore')
	event.add('forge:ores/deepslate/gold', 'minecraft:deepslate_gold_ore')
	event.add('forge:ores/deepslate/hureaulite', 'tinkers_reforged:deepslate_hureaulite_ore')
	event.add('forge:ores/deepslate/inferium', 'mysticalagriculture:deepslate_inferium_ore')
	event.add('forge:ores/deepslate/iron', 'minecraft:deepslate_iron_ore')
	event.add('forge:ores/deepslate/lapis', 'minecraft:deepslate_lapis_ore')
	event.add('forge:ores/deepslate/lead', 'immersiveengineering:deepslate_ore_lead')
	event.add('forge:ores/deepslate/lead', 'mekanism:deepslate_lead_ore')
	event.add('forge:ores/deepslate/lead', 'thermal:deepslate_lead_ore')
	event.add('forge:ores/deepslate/nickel', 'immersiveengineering:deepslate_ore_nickel')
	event.add('forge:ores/deepslate/nickel', 'thermal:deepslate_nickel_ore')
	event.add('forge:ores/deepslate/niter', 'thermal:deepslate_niter_ore')
	event.add('forge:ores/deepslate/osmium', 'mekanism:deepslate_osmium_ore')
	event.add('forge:ores/deepslate/prosperity', 'mysticalagriculture:deepslate_prosperity_ore')
	event.add('forge:ores/deepslate/red_beryl', 'tinkers_reforged:deepslate_red_beryl_ore')
	event.add('forge:ores/deepslate/redstone', 'minecraft:deepslate_redstone_ore')
	event.add('forge:ores/deepslate/silver', 'immersiveengineering:deepslate_ore_silver')
	event.add('forge:ores/deepslate/silver', 'thermal:deepslate_silver_ore')
	event.add('forge:ores/deepslate/sulfur', 'thermal:deepslate_sulfur_ore')
	event.add('forge:ores/deepslate/tin', 'mekanism:deepslate_tin_ore')
	event.add('forge:ores/deepslate/tin', 'thermal:deepslate_tin_ore')
	event.add('forge:ores/deepslate/uranium', 'immersiveengineering:deepslate_ore_uranium')
	event.add('forge:ores/deepslate/uranium', 'mekanism:deepslate_uranium_ore')
	event.add('forge:ores/deepslate/zinc', 'create:deepslate_zinc_ore')

	// Nether Ore Dictionary
	event.add('forge:ores/nether/ancient_debris', 'minecraft:ancient_debris')
	event.add('forge:ores/nether/cobalt', 'tconstruct:cobalt_ore')
	event.add('forge:ores/nether/dimensional_shard', 'rftoolsbase:dimensionalshard_nether')
	event.add('forge:ores/nether/gold', 'minecraft:nether_gold_ore')
	event.add('forge:ores/nether/inferium', 'mysticalagradditions:nether_inferium_ore')
	event.add('forge:ores/nether/prosperity', 'mysticalagradditions:nether_prosperity_ore')
	event.add('forge:ores/nether/quartz', 'minecraft:nether_quartz_ore')

	// End Ore Dictionary
	event.add('forge:ores/end/dimensional_shard', 'rftoolsbase:dimensionalshard_end')
	event.add('forge:ores/end/inferium', 'mysticalagradditions:end_inferium_ore')
	event.add('forge:ores/end/kepu', 'tinkers_reforged:kepu_ore')
	event.add('forge:ores/end/prosperity', 'mysticalagradditions:end_prosperity_ore')

	// Raw Ore Dictionary
	event.add('forge:ores/raw/uranium', 'exnihilosequentia:raw_uranium')
	event.add('forge:ores/raw/platinum', 'exnihilosequentia:raw_platinum')
	event.add('forge:ores/raw/aluminum', 'exnihilosequentia:raw_aluminum')
	event.add('forge:ores/raw/tin', 'exnihilosequentia:raw_tin')
	event.add('forge:ores/raw/silver', 'exnihilosequentia:raw_silver')
	event.add('forge:ores/raw/nickel', 'exnihilosequentia:raw_nickel')
	event.add('forge:ores/raw/lead', 'exnihilosequentia:raw_lead')
	event.add('forge:ores/raw/zinc', 'exnihilosequentia:raw_zinc')

	// Raw Block Dictionary
	event.add('forge:ores/rawblock/aluminum', 'immersiveengineering:raw_block_aluminum')
	event.add('forge:ores/rawblock/aluminum', 'tinkers_reforged:raw_aluminum_block')
	event.add('forge:ores/rawblock/cobalt', 'tconstruct:raw_cobalt_block')
	event.add('forge:ores/rawblock/copper', 'minecraft:raw_copper_block')
	event.add('forge:ores/rawblock/gold', 'minecraft:raw_gold_block')
	event.add('forge:ores/rawblock/iron', 'minecraft:raw_iron_block')
	event.add('forge:ores/rawblock/kepu', 'tinkers_reforged:raw_kepu_block')
	event.add('forge:ores/rawblock/lead', 'immersiveengineering:raw_block_lead')
	event.add('forge:ores/rawblock/lead', 'mekanism:block_raw_lead')
	event.add('forge:ores/rawblock/lead', 'thermal:raw_lead_block')
	event.add('forge:ores/rawblock/nickel', 'immersiveengineering:raw_block_nickel')
	event.add('forge:ores/rawblock/nickel', 'thermal:raw_nickel_block')
	event.add('forge:ores/rawblock/osmium', 'mekanism:block_raw_osmium')
	event.add('forge:ores/rawblock/silver', 'immersiveengineering:raw_block_silver')
	event.add('forge:ores/rawblock/silver', 'thermal:raw_silver_block')
	event.add('forge:ores/rawblock/tin', 'mekanism:block_raw_tin')
	event.add('forge:ores/rawblock/tin', 'thermal:raw_tin_block')
	event.add('forge:ores/rawblock/uranium', 'immersiveengineering:raw_block_uranium')
	event.add('forge:ores/rawblock/uranium', 'mekanism:block_raw_uranium')
	event.add('forge:ores/rawblock/zinc', 'create:raw_zinc_block')

	// Raw Ingot Dictionary
	event.add('forge:ores/rawingot/aluminum', 'immersiveengineering:raw_aluminum')
	event.add('forge:ores/rawingot/aluminum', 'tinkers_reforged:raw_aluminum')
	event.add('forge:ores/rawingot/cobalt', 'tconstruct:raw_cobalt')
	event.add('forge:ores/rawingot/copper', 'minecraft:raw_copper')
	event.add('forge:ores/rawingot/gold', 'minecraft:raw_gold')
	event.add('forge:ores/rawingot/iron', 'minecraft:raw_iron')
	event.add('forge:ores/rawingot/kepu', 'tinkers_reforged:raw_kepu')
	event.add('forge:ores/rawingot/lead', 'immersiveengineering:raw_lead')
	event.add('forge:ores/rawingot/lead', 'mekanism:raw_lead')
	event.add('forge:ores/rawingot/lead', 'thermal:raw_lead')
	event.add('forge:ores/rawingot/nickel', 'immersiveengineering:raw_nickel')
	event.add('forge:ores/rawingot/nickel', 'thermal:raw_nickel')
	event.add('forge:ores/rawingot/osmium', 'mekanism:raw_osmium')
	event.add('forge:ores/rawingot/silver', 'immersiveengineering:raw_silver')
	event.add('forge:ores/rawingot/silver', 'thermal:raw_silver')
	event.add('forge:ores/rawingot/tin', 'mekanism:raw_tin')
	event.add('forge:ores/rawingot/tin', 'thermal:raw_tin')
	event.add('forge:ores/rawingot/tin', 'thermal:raw_tin')
	event.add('forge:ores/rawingot/uranium', 'immersiveengineering:raw_uranium')
	event.add('forge:ores/rawingot/uranium', 'mekanism:raw_uranium')
	event.add('forge:ores/rawingot/zinc', 'create:raw_zinc')

	// Nuggets
	event.add('forge:nuggets/experience', 'create:experience_nugget')

	// Coins
	event.add('forge:coins/brass', 'createdeco:brass_coin')
	event.add('forge:coins/cast_iron', 'createdeco:cast_iron_coin')
	event.add('forge:coins/copper', 'createdeco:copper_coin')
	event.add('forge:coins/gold', 'createdeco:gold_coin')
	event.add('forge:coins/iron', 'createdeco:iron_coin')
	event.add('forge:coins/netherite', 'createdeco:netherite_coin')
	event.add('forge:coins/zinc', 'createdeco:zinc_coin')
	event.add('forge:coinstack/brass', 'createdeco:brass_coinstack')
	event.add('forge:coinstack/cast_iron', 'createdeco:cast_iron_coinstack')
	event.add('forge:coinstack/copper', 'createdeco:copper_coinstack')
	event.add('forge:coinstack/gold', 'createdeco:gold_coinstack')
	event.add('forge:coinstack/iron', 'createdeco:iron_coinstack')
	event.add('forge:coinstack/netherite', 'createdeco:netherite_coinstack')
	event.add('forge:coinstack/zinc', 'createdeco:zinc_coinstack')

	// Book tag fot Lectern and Eccentric Tome
	event.add('forge:books/guide', 'citadel:citadel_book')
	event.add('forge:books/guide', 'cookingforblockheads:crafting_book')
	event.add('forge:books/guide', 'cookingforblockheads:no_filter_edition')
	event.add('forge:books/guide', 'cookingforblockheads:recipe_book')
	event.add('forge:books/guide', 'create_enchantment_industry:enchanting_guide')
	event.add('forge:books/guide', 'eccentrictome:tome')
	event.add('forge:books/guide', 'immersiveengineering:manual')
	event.add('forge:books/guide', 'patchouli:guide_book')
	event.add('forge:books/guide', 'rftoolsbase:manual')
	event.add('forge:books/guide', 'tinkers_reforged:reforging_guide')
	event.add('minecraft:lectern_books', 'eccentrictome:tome')

	// Get the #forge:tag tag collection and remove mod:item from it
	// event.remove('forge:ingots\brick', 'supplementaries:ash_brick')
	// Remove Baolian ingot, Piroot ingot nuggets tag
	event.remove('balm:nuggets', 'tinkers_reforged:baolian_ingot')
	event.remove('balm:nuggets', 'tinkers_reforged:piroot_ingot')
	event.remove('forge:nuggets', 'tinkers_reforged:baolian_ingot')
	event.remove('forge:nuggets', 'tinkers_reforged:piroot_ingot')

	
	
	// Removes all tags from this entry
	// event.removeAllTagsFrom('minecraft:stick')
})


// 'advancednetherite:netherite_iron_ingot'
// 'advancednetherite:netherite_gold_ingot'
// 'advancednetherite:netherite_emerald_ingot'
// 'advancednetherite:netherite_diamond_ingot'
